version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: reta_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    working_dir: /var/www/html
    depends_on:
      - queue
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - DB_CONNECTION=mysql
      - DB_HOST=sql10.freesqldatabase.com
      - DB_PORT=3306
      - DB_DATABASE=sql10791792
      - DB_USERNAME=sql10791792
      - DB_PASSWORD=D2JITWbfbh

  queue:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: queue
    container_name: reta_queue
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=sql10.freesqldatabase.com
      - DB_PORT=3306
      - DB_DATABASE=sql10791792
      - DB_USERNAME=sql10791792
      - DB_PASSWORD=D2JITWbfbh
    command: php /var/www/html/artisan queue:work --sleep=3 --tries=3 --timeout=90
    depends_on:
      - app

  node:
    image: node:18
    container_name: reta_node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: tail -f /dev/null

volumes:
  db_data:
