version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reta_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    working_dir: /var/www/html
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - DB_CONNECTION=mysql
      - DB_HOST=sql10.freesqldatabase.com
      - DB_PORT=3306
      - DB_DATABASE=sql10791792
      - DB_USERNAME=sql10791792
      - DB_PASSWORD=D2JITWbfbh

  db:
    image: mysql:8
    container_name: reta_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: reta
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: reta
      MYSQL_PASSWORD: reta
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: