services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: reta_app
    ports:
      - "8080:80"
    # REMOVIDO VOLUME para evitar sobrescrever código copiado no build
    depends_on:
      - node
    command: >
      sh -c "php artisan config:cache && \
             php artisan migrate --force && \
             php artisan sync:deputados && \
             php artisan sync:despesas && \
             apache2-foreground || true"

  queue:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: reta_queue
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
    command: >
      sh -c "php artisan queue:work"

  node:
    image: node:18
    container_name: reta_node
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    command: tail -f /dev/null

volumes:
  db_data: