services:
  - type: web
    name: reta-projeto
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./docker/Dockerfile
    startCommand: apache2-foreground
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql10.freesqldatabase.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: sql10791792
      - key: DB_USERNAME
        value: sql10791792
      - key: DB_PASSWORD
        value: D2JITWbfbh